# vim: set syntax=python:

def build(bld):
    t = bld.program(
        name = 'cs2.e',
        source = 'cs2.c',
        target = 'cs2.e',
        use = ['calstis', 'imphttab'] + bld.env.LOCAL_LIBS,
        lib = bld.env.EXTERNAL_LIBS,
        libpath = bld.env.LIBPATH,
        rpath=bld.env.LIBPATH_CFITSIO,
        install_path = '${PREFIX}/bin'
        )
