import os

def build(bld):
    t = bld(
        features = ['cc', 'cprogram'],
        source = 'cs0.c',
        target = 'cs0.e',
        includes = [
            bld.env.INCLUDEDIR, # the hstcal include directory
            '.',
            '../include'
            ],
        # The order of these libraries is important
        uselib_local = ['calstis'] + bld.env.LOCAL_LIBS,
        lib = bld.env.EXTERNAL_LIBS,
        libpath = bld.env.LIBPATH,
        install_path = '${PREFIX}/bin',
        uselib = 'CFITSIO'
        )
    
