# vim: set syntax=python:

def build(bld):
    t = bld.stlib(
        source = [
            'hstio.c',
            'numeric.c',
            'keyword.c'
            ],
        target = 'hstio',
        uselib = ['CFITSIO'],
        install_path = bld.env.INSTALL_LIB and '${PREFIX}/lib'
        )
