# vim: set syntax=python:

def build(bld):
    t = bld.program(
        name = 'calacs.e',
        source = 'acsmain.c',
        target = 'calacs.e',
        use = ['hstcallib', 'calacs', 'imphttab'] + bld.env.LOCAL_LIBS,
        lib = bld.env.EXTERNAL_LIBS,
        libpath = bld.env.LIBPATH,
        install_path = '${PREFIX}/bin'
        )
