# vim: set syntax=python:
import os

def build_test(bld, name):
    return bld.program(
        source = name,
        target = os.path.splitext(name)[0],
        use = bld.env.LOCAL_LIBS,
        lib = bld.env.EXTERNAL_LIBS,
        libpath = bld.env.LIBPATH,
        install_path = '${PREFIX}/bin/test'
        )

def build(bld):
    for x in os.listdir(bld.path.abspath()):
        if x.startswith('test') and x.endswith('.c'):
            build_test(bld, x)
