# vim: set syntax=python:

SUBDIRS = [
    'lib',
    'cs0',
    'cs1',
    'cs2',
    'cs4',
    'cs6',
    'cs7',
    'cs11',
    'cs12'
    ]

def build(bld):
    for subdir in SUBDIRS:
        bld.recurse(subdir)
