# vim: set syntax=python:

def build(bld):
    t = bld.stlib(
        source = [
            'c_iraf_priv.c',
            'irafinit.c',
            ],
        target = 'cvos',
        install_path = bld.env.INSTALL_LIB and '${PREFIX}/lib'
        )
