#!/bin/sh
# STSDAS contains some code from the Numerical Recipes book.  We
# have licenses to use it and distribute binaries, but not to distribute
# source code.  
#
# When making a source distribution, run this script in the checked
# out source directory to delete all the code that is encumbered
# by the copyright.
#
#	cd release_tools
# 	./de_numrec

awk '{ print $1 }' < numrec_list.txt | (
	cd ..
	while read f
	do
		if rm $f
		then
			echo 'this source file is not available because it contains licensed code from the book Numerical Recipes' > $f
		else
			# make it really hard to miss any problems
			echo unable to remove $f
			exit 1
		fi
	done
	)
