# vim: set syntax=python:

def build(bld):
    t = bld.program(
        name = 'wf3rej.e',
        source = 'mainrej.c',
        target = 'wf3rej.e',
        use = ['calwf3', 'imphttab'] + bld.env.LOCAL_LIBS,
        lib = bld.env.EXTERNAL_LIBS,
        libpath = bld.env.LIBPATH,
        install_path = '${PREFIX}/bin'
        )
