# vim: set syntax=python:

def build(bld):
    t = bld.stlib(
        source = [
            'dummy.c',
            'hstcalversion.c'
            ],
        target = 'hstcallib',
        includes = ['../include/',
                    '../cfitsio',
                    ],
        use = ['CFITSIO', 'OPENMP'],
        install_path = bld.env.INSTALL_LIB and '${PREFIX}/lib'
        )
