# vim: set syntax=python:

def build(bld):
    t = bld.program(
        name = 'wf32d.e',
        source = 'main2d.c',
        target = 'wf32d.e',
        use = ['hstcallib', 'calwf3', 'imphttab'] + bld.env.LOCAL_LIBS,
        lib = bld.env.EXTERNAL_LIBS,
        libpath = bld.env.LIBPATH,
        rpath=bld.env.LIBPATH_CFITSIO,
        install_path = '${PREFIX}/bin'
        )
