import os

def build(bld):
    t = bld.stlib(
        source = """
            c_imt.c addCol.c ctables.c c_tbagt.c c_tbapt.c
            c_tbcdef1.c c_tbcfnd1.c c_tbciga.c c_tbcigi.c c_tbcigt.c
            c_tbcinf.c c_tbcnum.c c_tbegt.c c_tbept.c c_tbfpri.c c_tbfres.c
            c_tbhad.c c_tbhcal.c c_tbhgcm.c c_tbhgnp.c c_tbhgt.c c_tbhpcm.c
            c_tbhptt.c c_tbparse.c c_tbpsta.c c_tbrcsc.c c_tbrgtr.c
            c_tbrudf.c c_tbtacc.c c_tbtclo.c c_tbtcre.c c_tbtnam.c
            c_tbtopn.c initCol.c tbCopyTmpl.c tbHeader.c tbl_util.c
            tbSaveInfo.c c_phopar.c
            """,
        target = 'xtables',
        install_path = bld.env.INSTALL_LIB and '${PREFIX}/lib',
        use = 'CFITSIO'
        )
