# vim: set syntax=python:

def build(bld):
    t = bld(
        features = ['cc', 'cprogram'],
        source = ['test_getphttab.c', 'getphttab.c'],
        target = 'testphot.e',
        includes = [
            bld.env.INCLUDEDIR, # the hstcal include directory
            '.',
            '../include'
            ],
        # The order of these libraries is important
        uselib_local = ['calacs'] + bld.env.LOCAL_LIBS,
        uselib = ['CFITSIO'],
        lib = bld.env.EXTERNAL_LIBS,
        libpath = bld.env.LIBPATH,
        install_path = '${PREFIX}/bin'
        )
        
    t2 = bld(
        features = ['cc', 'cstaticlib'],
        source = ['test_getphttab.c', 'getphttab.c'],
        target = 'imphttab',
        includes = [
            bld.env.INCLUDEDIR, # the hstcal include directory
            '.',
            '../include'
            ],
        # The order of these libraries is important
        uselib_local = ['calacs'] + bld.env.LOCAL_LIBS,
        uselib = ['CFITSIO'],
        lib = bld.env.EXTERNAL_LIBS,
        libpath = bld.env.LIBPATH,
        install_path = '${PREFIX}/lib'
        )
    
