# vim: set syntax=python:

def build(bld):
    t = bld.program(
        source = ['test_getphttab.c', 'getphttab.c'],
        target = 'testphot.e',
        # The order of these libraries is important
        use = ['calacs'] + bld.env.LOCAL_LIBS,
        lib = bld.env.EXTERNAL_LIBS,
        libpath = bld.env.LIBPATH,
        install_path = bld.env.INSTALL_TEST and '${PREFIX}/bin'
        )

    t2 = bld.stlib(
        source = ['test_getphttab.c', 'getphttab.c'],
        target = 'imphttab',
        # The order of these libraries is important
        use = ['calacs'] + bld.env.LOCAL_LIBS,
        lib = bld.env.EXTERNAL_LIBS,
        libpath = bld.env.LIBPATH,
        install_path = bld.env.INSTALL_LIB and '${PREFIX}/lib'
        )
