# vim: set syntax=python:

def build(bld):
    #bld.program(
    #    source = ['test_getphttab.c', 'getphttab.c'],
    #    target = 'testphot.e',
    #    # The order of these libraries is important
    #    use = ['calacs'] + bld.env.LOCAL_LIBS,
    #    lib = bld.env.EXTERNAL_LIBS,
    #    libpath = bld.env.LIBPATH,
    #    install_path = bld.env.INSTALL_TEST and '${PREFIX}/bin'
    #    )

    bld.stlib(
        source = ['getphttab.c'],
        target = 'imphttab',
        # The order of these libraries is important
        use = bld.env.LOCAL_LIBS,
        lib = bld.env.EXTERNAL_LIBS,
        libpath = bld.env.LIBPATH,
        rpath=bld.env.LIBPATH_CFITSIO,
        install_path = bld.env.INSTALL_LIB and '${PREFIX}/lib'
        )
