# vim: set syntax=python:

def build(bld):
    t = bld.program(
        source = 'maincte.c',
        target = 'wf3cte.e',
        use = ['hstcallib', 'calwf3', 'imphttab'] + bld.env.LOCAL_LIBS,
        lib = bld.env.EXTERNAL_LIBS,
        libpath = bld.env.LIBPATH,
        rpath=bld.env.LIBPATH_CFITSIO,
        install_path = '${PREFIX}/bin'
        )
