# vim: set syntax=python:

def build(bld):
    bld(
        # Use Fortran
        features = ['fc', 'fcstlib'],
        source = [
            'ncarfft.f'
            ],
        target = 'applib',
        install_path = bld.env.INSTALL_LIB and '${PREFIX}/lib',
        )
