# vim: set syntax=python:

def build(bld):
    bld(
        features = ['cc', 'cstaticlib'],
        source = [
            'ncarfft.f'
            ],
        target = 'applib',
        install_path = '${PREFIX}/lib',
        )
    
    
