# vim: set syntax=python:

def build(bld):
    t = bld.program(
        source = 'maincte.c',
        target = 'acscte.e',
        use = ['calacs', 'imphttab'] + bld.env.LOCAL_LIBS,
        lib = bld.env.EXTERNAL_LIBS,
        libpath = bld.env.LIBPATH,
        install_path = '${PREFIX}/bin'
        )

