# vim: set syntax=python:

SUBDIRS = [
    'lib',
    'calwf3',
    'wf3ccd',
    'wf3rej',
    'wf3cte',
    'wf3ir',
    'wf32d',
    'wf3sum',
    ]

def build(bld):
    for subdir in SUBDIRS:
        bld.recurse(subdir)

    bld(name='wf3',
        depends_on=[
            'calwf3.e',
            'wf3ccd.e',
            'wf3rej.e',
            'wf3cte.e',
            'wf3ir.e',
            'wf32d.e',
            'wf3sum.e'],
        always=True)
