# vim: set syntax=python:

SUBDIRS = [
    'lib',
    'calacs',
    'acsrej',
    'acssum',
    'acsccd',
    'acs2d'
    ]
            
def build(bld):
    for subdir in SUBDIRS:
        bld.recurse(subdir)
