name: When PR Opened

on:
  pull_request_target:
    types:
    - opened

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Label PR
      uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
